[package]
name = "generative-art-schotter-rust"
version = "0.1.0"
edition = "2021"
authors = ["Janusz Piechówka"]
repository = "https://github.com/jpiechowka/generative-art-schotter-rust"
license = "MIT OR Apache-2.0"

[dependencies]
nannou = "0.19.0"
